apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tram.fullname" . }}-pipeline-services
  labels:
    {{- include "tram.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tram.fullname" . }}-pipeline-services
  labels:
    {{- include "tram.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tram.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tram.fullname" . }}-pipeline-services
