{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tram.fullname" . }}-ui
  labels:
    {{- include "tram.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  {{- with .Values.ui.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ui.serviceType }}
  ports:
    - port: {{ .Values.ui.port }}
      targetPort: http
      protocol: TCP
      name: http-ui
      {{- if and (eq .Values.ui.serviceType "NodePort") .Values.ui.nodePort }}
      nodePort: {{ .Values.ui.nodePort }}
      {{- end }}
  selector:
    {{- include "tram.selectorLabels" . | nindent 4 }}
{{- end }}
