"""Import all transforms to trigger @register_transform decorators."""

from tram.transforms.add_field import AddFieldTransform  # noqa: F401
from tram.transforms.aggregate import AggregateTransform  # noqa: F401
from tram.transforms.cast import CastTransform  # noqa: F401
from tram.transforms.coalesce_fields import CoalesceFieldsTransform  # noqa: F401
from tram.transforms.deduplicate import DeduplicateTransform  # noqa: F401
from tram.transforms.drop import DropTransform  # noqa: F401
from tram.transforms.enrich import EnrichTransform  # noqa: F401
from tram.transforms.explode import ExplodeTransform  # noqa: F401
from tram.transforms.filter_rows import FilterRowsTransform  # noqa: F401
from tram.transforms.flatten import FlattenTransform  # noqa: F401
from tram.transforms.hex_decode import HexDecodeTransform  # noqa: F401
from tram.transforms.inject_meta import InjectMetaTransform  # noqa: F401
from tram.transforms.jmespath_extract import JmesPathExtractTransform  # noqa: F401
from tram.transforms.json_flatten import JsonFlattenTransform  # noqa: F401
from tram.transforms.limit import LimitTransform  # noqa: F401
from tram.transforms.mask import MaskTransform  # noqa: F401
from tram.transforms.melt import MeltTransform  # noqa: F401
from tram.transforms.project import ProjectTransform  # noqa: F401
from tram.transforms.regex_extract import RegexExtractTransform  # noqa: F401
from tram.transforms.rename import RenameTransform  # noqa: F401
from tram.transforms.select_from_list import SelectFromListTransform  # noqa: F401
from tram.transforms.sort import SortTransform  # noqa: F401
from tram.transforms.template import TemplateTransform  # noqa: F401
from tram.transforms.timestamp_normalize import TimestampNormalizeTransform  # noqa: F401
from tram.transforms.unnest import UnnestTransform  # noqa: F401
from tram.transforms.validate import ValidateTransform  # noqa: F401
from tram.transforms.value_map import ValueMapTransform  # noqa: F401
