"""Import all connectors to trigger registration decorators."""

from tram.connectors.amqp import sink as _amqp_sink  # noqa: F401
from tram.connectors.amqp import source as _amqp_source  # noqa: F401
from tram.connectors.azure_blob import sink as _azure_blob_sink  # noqa: F401
from tram.connectors.azure_blob import source as _azure_blob_source  # noqa: F401
from tram.connectors.elasticsearch import sink as _elasticsearch_sink  # noqa: F401
from tram.connectors.elasticsearch import source as _elasticsearch_source  # noqa: F401
from tram.connectors.ftp import sink as _ftp_sink  # noqa: F401
from tram.connectors.ftp import source as _ftp_source  # noqa: F401
from tram.connectors.gcs import sink as _gcs_sink  # noqa: F401
from tram.connectors.gcs import source as _gcs_source  # noqa: F401
from tram.connectors.gnmi import source as _gnmi_source  # noqa: F401
from tram.connectors.influxdb import sink as _influxdb_sink  # noqa: F401
from tram.connectors.influxdb import source as _influxdb_source  # noqa: F401
from tram.connectors.kafka import sink as _kafka_sink  # noqa: F401
from tram.connectors.kafka import source as _kafka_source  # noqa: F401
from tram.connectors.local import sink as _local_sink  # noqa: F401
from tram.connectors.local import source as _local_source  # noqa: F401
from tram.connectors.mqtt import sink as _mqtt_sink  # noqa: F401
from tram.connectors.mqtt import source as _mqtt_source  # noqa: F401
from tram.connectors.nats import sink as _nats_sink  # noqa: F401
from tram.connectors.nats import source as _nats_source  # noqa: F401
from tram.connectors.opensearch import sink as _opensearch_sink  # noqa: F401
from tram.connectors.prometheus_rw import source as _prometheus_rw_source  # noqa: F401
from tram.connectors.redis import sink as _redis_sink  # noqa: F401
from tram.connectors.redis import source as _redis_source  # noqa: F401
from tram.connectors.rest import sink as _rest_sink  # noqa: F401
from tram.connectors.rest import source as _rest_source  # noqa: F401
from tram.connectors.s3 import sink as _s3_sink  # noqa: F401
from tram.connectors.s3 import source as _s3_source  # noqa: F401
from tram.connectors.sftp import sink as _sftp_sink  # noqa: F401
from tram.connectors.sftp import source as _sftp_source  # noqa: F401
from tram.connectors.snmp import sink as _snmp_sink  # noqa: F401
from tram.connectors.snmp import source as _snmp_source  # noqa: F401
from tram.connectors.sql import sink as _sql_sink  # noqa: F401
from tram.connectors.sql import source as _sql_source  # noqa: F401
from tram.connectors.syslog import source as _syslog_source  # noqa: F401
from tram.connectors.ves import sink as _ves_sink  # noqa: F401
from tram.connectors.webhook import source as _webhook_source  # noqa: F401
from tram.connectors.websocket import sink as _websocket_sink  # noqa: F401
from tram.connectors.websocket import source as _websocket_source  # noqa: F401
from tram.connectors.clickhouse import sink as _clickhouse_sink  # noqa: F401
from tram.connectors.clickhouse import source as _clickhouse_source  # noqa: F401
from tram.connectors.corba import source as _corba_source  # noqa: F401
