apiVersion: v2
name: tram
description: TRAM — Trishul Real-time Aggregation & Mediation
type: application
version: 1.0.5
appVersion: "1.0.5"
keywords:
  - data-pipeline
  - adapter
  - mapper
  - streaming
home: https://github.com/trishul/tram
sources:
  - https://github.com/trishul/tram
maintainers:
  - name: TRAM Maintainers
