apiVersion: v2
name: trishul-ram
description: TRAM — Trishul Real-time Aggregation & Mediation
type: application
version: 1.2.3
appVersion: "1.2.3"
keywords:
  - data-pipeline
  - adapter
  - mapper
  - streaming
home: https://github.com/trishul/tram
sources:
  - https://github.com/trishul/tram
maintainers:
  - name: TRAM Maintainers

dependencies:
  - name: postgresql
    version: "16.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
